name: Test
on: [pull_request]
jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/setup-node@v4
                with:
                 node-version: latest
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm i
            - run: npm run test:all
